Homework2
evgmolt/ASP_NET_Core pull request #2
Opened 2021-03-22 09:59 UTC by evgmolt

2021-03-23 21:01 UTC, Forkosigan requested changes

2021-03-23 21:01 UTC, Forkosigan commented on MetricsManager/MetricsAgent/Controllers/CpuMetricsController.cs
> +        [HttpGet("agent/{agentId}/from/{fromTime}/to/{toTime}")]
Немного в методичке накосячили. в route агента разумеется agent/{agentId} не надо , так как агент собирает данные только с себя самого. и во все методах все контороллеров лежащих в MetricsAgent (в MetricaManager все оставить как есть!) надо сделать аналогично. Методичку я уже поправил

2021-03-23 21:01 UTC, Forkosigan commented on MetricsManager/MetricsManager/Controllers/Enums/Percentile.cs
> +    public enum Percentile
Лучше вынести в отдельный проект библиотек этот класс. Так как он должен быть заюзан и в MetricsAgent и в MetricsManager. Агент тоже должен уметь возраать метрики CPU по перцентилям

2021-03-24 04:00 UTC, evgmolt commented on MetricsManager/MetricsAgent/Controllers/CpuMetricsController.cs
> +        [HttpGet("agent/{agentId}/from/{fromTime}/to/{toTime}")]
Спасибо! А я долго ломал голову, для чего здесь agent. Коллегам в Telegram написал.

2021-03-24 04:53 UTC, merged