Homework6
evgmolt/ASP_NET_Core pull request #7
Opened 2021-04-14 10:21 UTC by evgmolt

2021-04-17 13:16 UTC, Forkosigan requested changes

2021-04-17 13:16 UTC, Forkosigan commented on MetricsManager/MetricsManager/DAL/Repositories/AgentsRepository.cs
> +    public class IAgentsRepository : IAgentsRepository<AgentInfo>
Классы не называют с I. Только интерфейсы

2021-04-17 13:16 UTC, Forkosigan commented on MetricsManager/MetricsManager/DAL/Repositories/AgentsRepository.cs
> +            this._configuration = configuration;
не используйте this. Это лишнее. Это вобщем. А здесь конкретно не нужна _configuration вообще. Зачем. Реально то испольуезтся далее только _connectionString

2021-04-17 13:16 UTC, Forkosigan commented on MetricsManager/MetricsManager/Jobs/MetricJobs/CpuMetricJob.cs
> +                        CpuMetric lastmetric = _repository.GetLast(i);
в C# принят CamelCase для переменных. Настоятельно рекомендую - внимательно следить за всеми именованиями в коде и следовать best practices и принятым в сообществе стандартам

2021-04-17 13:16 UTC, Forkosigan commented on MetricsManager/MetricsManager/DAL/Repositories/CpuMetricsRepository.cs
> +        public CpuMetric GetLast(int agentid)
сюда передается из Job не AgentId а почему то индекс из цикла 
for (int i = 0; i < agents.Count(); i++)
Это конечно неверно

2021-04-17 13:16 UTC, Forkosigan commented on MetricsManager/MetricsManager/DAL/Repositories/CpuMetricsRepository.cs
> +                        "SELECT Id, AgentId, Time, Value FROM " + _tablename + " WHERE Id = (SELECT MAX(Id) FROM " + _tablename + ")",
вообще не понля этого запроса. Он точно не делает то что надо. Надо найти MAX(Time) среди всех элемнтов таблицы у которых AgentId = переданному парамерту agentId

2021-04-19 05:55 UTC, evgmolt commented on MetricsManager/MetricsManager/DAL/Repositories/CpuMetricsRepository.cs
> +        public CpuMetric GetLast(int agentid)
Но у  объекта AgentInfo нет внутри AgentId, поэтому используется индекс из цикла. Это неверно?

2021-04-20 03:23 UTC, merged